name: Push to DockerHub

on:
  push:
    branches: [ 'gr-main' ]

jobs:
  push:
    runs-on: ubuntu-latest
    environment: release
    env:
      IMAGE_NAME: gresearch/alerta
      WEBUI_SHA: e7575af4f3c38a6cdf9dbd1165b586a0849960c0
    steps:
      - name: Checkout docker-alerta
        uses: actions/checkout@v2
      - name: Checkout alerta-webui
        uses: actions/checkout@v2
        with:
          repository: 'G-Research/alerta-webui'
          path: 'alerta-webui'
      - name: Verify SHA
        working-directory: alerta-webui
        run: git merge-base --is-ancestor $WEBUI_SHA gr-main
      - name: Set variables
        id: vars
        run: |
          echo "VERSION=$(cat VERSION)" >> $GITHUB_OUTPUT
          echo "SHORT_COMMIT_ID=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Set Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.vars.outputs.VERSION }}
            type=raw,value=${{ steps.vars.outputs.SHORT_COMMIT_ID }}
      - name: Login to Docker Hub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build & Push Image
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            WEBUI_SHA=${{ env.WEBUI_SHA }}
            VERSION=${{ steps.vars.outputs.VERSION }}
          tags: ${{ steps.meta.outputs.tags }}
          push: ${{ github.ref_protected }} # only for protected branches
          labels: ${{ steps.meta.outputs.labels }}