name: Build and Test

on:
  pull_request:
  push:
    branches:
      - gr-main
      - gr-oss-330-alerta-contrib

jobs:
  test-postgres:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Lint
        id: docker-lint
        run: |
          docker run --rm -i ghcr.io/hadolint/hadolint hadolint \
          --ignore DL3008 \
          --ignore DL3059 \
          --ignore DL3003 \
          - < Dockerfile
      - name: Set variables
        id: vars
        run: |
          echo "VERSION=$(cat VERSION)" >> $GITHUB_OUTPUT
          echo "CONTRIB_SHA=$(cat CONTRIB_SHA)" >> $GITHUB_OUTPUT
          echo "WEBUI_SHA=$(cat WEBUI_VERSION)" >> $GITHUB_OUTPUT
      - name: Run tests
        id: smoketest
        run: |
          docker-compose -f tests/docker-compose.test.postgres.yml build \
            --build-arg VERSION=${{ steps.vars.outputs.VERSION }} \
            --build-arg WEBUI_SHA=${{ steps.vars.outputs.WEBUI_SHA }} \
            --build-arg CONTRIB_SHA=${{ steps.vars.outputs.CONTRIB_SHA }}
          docker-compose -f tests/docker-compose.test.postgres.yml up --exit-code-from tester

  test-mongodb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Lint
        id: docker-lint
        run: |
          docker run --rm -i ghcr.io/hadolint/hadolint hadolint \
          --ignore DL3008 \
          --ignore DL3059 \
          --ignore DL3003 \
          - < Dockerfile
      - name: Set variables
        id: vars
        run: |
          echo "VERSION=$(cat VERSION)" >> $GITHUB_OUTPUT
          echo "WEBUI_SHA=$(cat WEBUI_VERSION)" >> $GITHUB_OUTPUT
          echo "CONTRIB_SHA=$(cat CONTRIB_SHA)" >> $GITHUB_OUTPUT
      - name: Run tests
        id: smoketest
        run: |
          docker-compose -f tests/docker-compose.test.mongodb.yml build \
            --build-arg VERSION=${{ steps.vars.outputs.VERSION }} \
            --build-arg WEBUI_SHA=${{ steps.vars.outputs.WEBUI_SHA }} \
            --build-arg CONTRIB_SHA=${{ steps.vars.outputs.CONTRIB_SHA }}
          docker-compose -f tests/docker-compose.test.mongodb.yml up --exit-code-from tester
